[[blog_post]]
title = """
        Hello World !
        """
intro = """
        Finally. After more than two years of talking about it, I have a place to put my rants on. \
        I want to talk about the tech stack behind it and some choices i made. I ended up writing \
        my own blog engine and learn a bit in the process.\
        """
image = "/images/hello-world.jpg"
file_name = "/blog/hello-world.md"
