[[blog_post]]
title = """
        Hello World !
        """
intro = """
        Finally. After more than two years of talking about it, I have a place to put my rants on. \
        I want to talk about the tech stack behind it and some choices i made. I ended up writing \
        my own blog engine and learn a bit in the process.\
        """
image = "/images/hello-world.jpg"
file_name = "/blog/hello-world.md"

[[blog_post]]
title = """
        We should have caught it
        """
intro = """
        Where i get passionate about expertise and despair of the state of our field. \
        But hey, there are hope too. I hope @noahsussman is happy about the result. \
        """
image = "/images/gimli_glider.jpeg"
file_name = "/blog/we-should-have-caught-it.md"

[[unpublished_blog_post]]
title = """
        Famous incidents reading list
        """
intro = """
        A regularly updated list of incidents i learn from and material around learning from them
        """
image = "/images/arianneboom.png"
file_name = "/blog/famous-incidents-reading-list.md"


[[unpublished_blog_post]]
title = """
        Bringing Politics in Data Science
        """
intro = """
        Diving into a paper on making data science better for society by making \
        the field political. Let's try to apply a bit of control theory to the paper\
        """
image = "/images/research_ethics.png"
file_name = "/blog/bringing-politics-data-science.md"
